service: guarapo-todo-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}

plugins:
  - serverless-offline

functions:
  register:
    handler: src/routes/auth.registerHandler
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  login:
    handler: src/routes/auth.loginHandler
    timeout: 10
    events:
      - http:
          path: auth/login
          method: post
          cors: true