service: guarapo-todo-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}

plugins:
  - serverless-offline

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get