service: guarapo-todo-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}

plugins:
  - serverless-offline

functions:
  register:
    handler: src/routes/auth.registerHandler
    timeout: 60
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  login:
    handler: src/routes/auth.loginHandler
    timeout: 60
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  createList:
    handler: src/routes/list.createListHandler
    timeout: 60
    events:
      - http:
          path: lists
          method: post
          cors: true

  getLists:
    handler: src/routes/list.getListsHandler
    timeout: 60
    events:
      - http:
          path: lists
          method: get
          cors: true

  getTasks:
    handler: src/routes/task.getTasksHandler
    timeout: 60
    events:
      - http:
          path: lists/{id}/tasks
          method: get
          cors: true

  addTask:
    handler: src/routes/task.addTaskHandler
    timeout: 60
    events:
      - http:
          path: lists/{id}/tasks
          method: post
          cors: true

  completeTask:
    handler: src/routes/task.completeTaskHandler
    timeout: 60
    events:
      - http:
          path: tasks/{id}
          method: put
          cors: true

  deleteTask:
    handler: src/routes/task.deleteTaskHandler
    timeout: 60
    events:
      - http:
          path: tasks/{id}
          method: delete
          cors: true